### ISSUE TITLE
Password Stealing

### ISSUE THREAD

**Issue by PrimeBomb** [Nexure/RoSearcher#6]
Hey, some user on discord is calling your extension out for having the potential of stealing roblox accounts.
![unknown-5](https://user-images.githubusercontent.com/37458083/81355793-2a27ce00-9095-11ea-82cd-ef4a36836394.png)
Can you confirm that it doesnt and provide some proof? I really love using your extenstion and I dont wanna stop using it because your extenstion has been falsely accused of stealing accounts.

**Comment by clv-2** [comment]
> "Can you confirm that it doesnt and provide some proof?"
It definitely does not, and provide proof? You are posting this on the OPEN SOURCE GITHUB of the extension, you can see the only urls it contacts are roblox related urls; the guy is braindead and is just wanting spread mass panic

**Comment by PrimeBomb** [comment]
oops, didnt mean to close it, but thanks for the response, sorry if i seem a bit braindead, i never used this site, i only use it to make reports.

**Comment by clv-2** [comment]
All good, it's just annoying when people who don't know what they are talking about spread panic.

**Comment by clv-2** [comment]
If anyone knows the user or the server that is mainly spreading these rumors, please do let us know as we would like to keep everything clear.

**Comment by Nexure** [comment]
Clv pretty much said what I would've said. Closing the issue.

**Comment by PrimeBomb** [comment]
Alrighty, the app is Discord if you wanted to know, this users tag and stuff is: chartebar#2057 if you would like to speak with him and get confirmation about this situation.
If you dont mind, please update us on this situation because this has been posted to a whole server and has been sent out to thousands of users saying your extension is spyware.

**Comment by littlebroto1** [comment]
@clv-2  Well, looking for fetch is not a good way to find it. Javascript can be easily encoded so it does not appear like what it is supposed to. For example, `\u0066\u0065\u0074\u0063\u0068` could run the fetch function without anyone knowing. Also, there are ways to send requests through ways other than fetch. For example, you could send an `XMLHttpRequest` or its encoded version and do the same thing. And there is nothing preventing you from loading it from base64 or something like `window[atob('ZmV0Y2g=')];`. Now, I am not saying your program is necessarily bad, I am just putting it into perspective for those who don't know and showing the flaws of your current argument.

**Comment by clv-2** [comment]
Except it doesn't use any of the methods you mentioned to execute any http requests, there are no http requests found when using a program like Fiddler to check, and regarding editing the extension and cleaning it up on github, view the local extension source yourself and you can see the hashes line up with the ones on github. Stop trying to spread unneeded panic.

**Comment by elymltd** [comment]
The extension is legit and open source, just look at all the outgoing connections and it'll be very easy to tell what's going on.
